============================= test session starts ==============================
platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /Users/aorumbayev/MakerX/projects/decipher/algokit-unchained/projects/algokit-unchained-contracts
configfile: pyproject.toml
plugins: cov-5.0.0, anyio-4.4.0
collected 0 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting tests/poa_test.py ______________________
ImportError while importing test module '/Users/aorumbayev/MakerX/projects/decipher/algokit-unchained/projects/algokit-unchained-contracts/tests/poa_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/poa_test.py:8: in <module>
    from smart_contracts.artifacts.poa.client import PoaClient
E   ImportError: cannot import name 'PoaClient' from 'smart_contracts.artifacts.poa.client' (/Users/aorumbayev/MakerX/projects/decipher/algokit-unchained/projects/algokit-unchained-contracts/smart_contracts/artifacts/poa/client.py)
- generated xml file: /Users/aorumbayev/MakerX/projects/decipher/algokit-unchained/projects/algokit-unchained-contracts/pytest-junit.xml -

---------- coverage: platform darwin, python 3.12.4-final-0 ----------
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
smart_contracts/__init__.py                   0      0   100%
smart_contracts/artifacts/poa/client.py     199     90    55%
tests/__init__.py                             0      0   100%
tests/conftest.py                            18      6    67%
tests/poa_test.py                            21     14    33%
-------------------------------------------------------------
TOTAL                                       238    110    54%

=========================== short test summary info ============================
ERROR tests/poa_test.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.09s ===============================
